name: Application Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

jobs:
  # ==========================================================================
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag techmago/teste:master-${GITHUB_RUN_NUMBER}

  # ============================================================================
  deploy_developement:
    name: deploy_developement
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Pretend to work
        run: sleep 5  ; echo "success"

  # ============================================================================
  deploy_homologation:
    name: deploy_homologation
    runs-on: ubuntu-latest
    needs: [deploy_developement]
    environment:
      name: hml
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Pretend to work
        run: sleep 5  ; echo "success"

  # ============================================================================
  deploy_production:
    name: deploy_production
    runs-on: ubuntu-latest
    needs: [deploy_homologation]
    environment:
      name: prd
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Pretend to work
        run: sleep 5  ; echo "success"
