name: Infraestruture Pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - main

jobs:
  # ============================================--==============================
  infra_developement:
    name: infra developement
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Pretend to work
        run: sleep 5  ; echo "success"
  # ==================================================--========================
  infra_homologation:
    name: infra homologation
    runs-on: ubuntu-latest
    needs: [infra_developement]
    environment:
      name: hml
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Pretend to work
        run: sleep 5  ; echo "success"

  # ============================================================================
  infra_production:
    name: infra production
    runs-on: ubuntu-latest
    needs: [infra_homologation]
    environment:
      name: prd
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Pretend to work
        run: sleep 5  ; echo "success"
