name: Infraestruture Pipeline
on:
  push:
    branches: [ main ]
    paths:
      - kube/file.yml
jobs:
  # ============================================================================
  infra_developement:
    name: infra developement
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Pretend to work
        run: sleep 5  ; echo "success"

  # ============================================================================
  infra_production:
    name: infra production
    runs-on: ubuntu-latest
    needs: [infra_developement]
    environment:
      name: prd
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Pretend to work
        run: sleep 5  ; echo "success"
